### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-python#99]
Once I've fixed the currently failing tests in #94, I'll setup a CI pipeline for this repo to avoid silent failures like this in the future.

Steps towards closing this:
- [ ] Fix the build & spring-clean dependencies (done in #177)
- [ ] Add pipeline on GH actions to run tests (done in #177)
- [ ] Add devcontainer with GDAL installed (done in #177)
- [ ] Add linting
